//Page to scrape OFA data
//https://script.googleusercontent.com/macros/echo?user_content_key=ppaeWcFgTPK1Hjlset-8iKm66vf0RkzOthG4h1IPdAS3Gg83099Yeb8AwjH3VGc5dkVWTFvFOohjgV0EcShmR3sKPUK1ovYpOJmA1Yb3SEsKFZqtv3DaNYcMrmhZHmUMWojr9NvTBuBLhyHCd5hHa1EECkhnGiRJAZI4bMbX5Ji0hxT5YYAjV582_JeCN40KcuKFPZ0H0fIcVTKObpOM3-FzdOMPwCfJAlELXCcbpSdQhfYX18E7Ti_wV7pyy1SHGkQD15PH0z3JMD7ozEDUeCXGlmbNzuB7btqlU2XPC6KfODeHxXcwh0ftzhWI3_v3YhiWPv9QcPN2ltxGddp6WHGwUxgbyORwPH4Vr3q7PIuOUB5Wk0hWIA&lib=Mwv9a3pgmJaGWMaDXqpunQQxD7rUy7zQ7

var seed = (function () {

// declaring seed data array using Organize for America data
var seedData = [
{
twitter: "repdonyoung",
denierquoteurl: "http://www.youtube.com/watch?v=NKcmjBBtxrs",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400440.jpg",
state: "AK",
denierstatement: "I think this is the biggest scam since the Teapot Dome.'",
role: "House",
lastname: "Young",
firstname: "Don",
party: "R"
},
{
twitter: "Robert_Aderholt",
denierquoteurl: "http://aderholt.house.gov/common/popup/popup.cfm?action=item.print&itemID=993",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400004.jpg",
state: "AL",
denierstatement: "I fall into the second group of people who believe, as do many very credible scientists, that the earth is currently in a natural warming cycle rather than a man-made climate change. Many scientists believe that natural cycles of warming and cooling have existed since the beginning of Earth. If we take the current models of climate prediction and apply those same models to what actually happened in the last thirty years, the models are shown to be very flawed. In addition, what knowledge we do have of a warming period in the Middle Ages cannot be explained by current models which are focused on greenhouse gas reductions.'",
role: "House",
lastname: "Aderholt",
firstname: "Robert",
party: "R",
district: 4
},
{
twitter: "RepMoBrooks",
denierquoteurl: "http://news.sciencemag.org/scienceinsider/2011/02/new-science-subcommittee-chair.html",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412395.jpg",
state: "AL",
denierstatement: "I'm also old enough to remember when the same left-wing part of our society was creating a global cooling scare in order to generate funds for their pet projects. So 30-some years ago the big scare was global cooling, and once they drained that [topic], they shifted to global warming. So I'm approaching the issue with a healthy degree of skepticism. If the evidence is there to prove it, then so be it.' (also numerous quotes from a March 31, 2011 committee hearing)",
role: "House",
lastname: "Brooks",
firstname: "Mo",
party: "R",
district: 5
},
{
twitter: "SenShelbyPress",
denierquoteurl: "http://toxicnation.blogspot.com/2008/01/part-ii-are-we-destroying-mother-earth.html",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/300089.jpg",
state: "AL",
denierstatement: "Global warming continues to be an issue of significant debate in Congress and throughout the scientific community. In addition, important scientific research is ongoing as there are still many questions that must be answered before we take steps to address this issue. For example, is the climate change phenomenon cyclical or is it a function of manmade pollutants, or both? I believe the science must be firmly grounded before we take any actions that could seriously cripple many sectors of our economy.'",
role: "Senate",
lastname: "Shelby",
firstname: "Richard",
party: "R"
},
{
twitter: "JohnBoozman",
denierquoteurl: "http://thinkprogress.org/climate/2010/09/13/174788/gop-senate-deniers/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400040.jpg",
state: "AR",
denierstatement: "Well I think that we’ve got perhaps climate change going on. The question is what’s causing it. Is man causing it, or, you know, is this a cycle that happens throughout the years, throughout the ages. And you can look back some of the previous times when there was no industrialization, you had these different ages, ice ages, and things warming and things. That’s the question.'",
role: "Senate",
lastname: "Boozman",
firstname: "John",
party: "R"
},
{
twitter: "RepRickCrawford",
denierquoteurl: "http://talkbusiness.net/2013/01/cong-crawford-wants-permanent-spending-controls/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412400.jpg",
state: "AR",
denierstatement: "He also fielded a question regarding climate change and President Obama’s environmental agenda. “There’s not sound science to support some of the initiatives that the President, I think, is committed to. We know that some of the research was faulty and it drove a lot of the agenda for a long time. and then it turned out there were some questions about the validity of that research.” “I don’t see a lot of the green initiatives that are being talked about being supported by scientific data, but more supported by political agendas.”",
role: "House",
lastname: "Crawford",
firstname: "Rick",
party: "R",
district: 1
},
{
twitter: "RepTimGriffin",
denierquoteurl: "http://www.thv11.com/news/story.aspx?storyid=102658",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412401.jpg",
state: "AR",
denierstatement: "“I am not convinced that the problem of global warming is what the scientists say it is. Particularly in light of the recent research, that demonstrates that there are a lot of shenanigans going on with the data.”",
role: "House",
lastname: "Griffin",
firstname: "Tim",
party: "R",
district: 2
},
{
twitter: "RepTrentFranks",
denierquoteurl: "http://www.azcentral.com/news/election/questionnaire2008/congress08.php?action=ViewAns&canname=frankst",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400141.jpg",
state: "AZ",
denierstatement: "I have yet to see clear and convincing evidence that it exists beyond historical fluctuations. ",
role: "House",
lastname: "Franks",
firstname: "Trent",
party: "R",
district: 8
},
{
twitter: "RepGosar",
denierquoteurl: "http://www.azcentral.com/news/politics/2012questionnaires/results.php?id=gosarp",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412397.jpg",
state: "AZ",
denierstatement: "Further, “global warming” now known as “climate change” is likely not in our control in any event. Historical records clearly demonstrate vast temperature swings long before Man arrived, from temperate zones in Alaska to ice ages in New York.",
role: "House",
lastname: "Gosar",
firstname: "Paul",
party: "R",
district: 4
},
{
twitter: "RepDavid",
denierquoteurl: "https://www.youtube.com/watch?v=MO6QCQ30f24",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412399.jpg",
state: "AZ",
denierstatement: "I don’t see the data. You know, I think I have a reasonably good statistics background. And I have not sat there with pages and pages of data. But when you think about the complexity of a worldwide system and the amount of data you’d have to capture, and how you adjust for a sunspot, and how you adjust for a hurricane and I think it’s incredibly arrogant for the Al Gores of the world to stand up and say the world is coming to an end. Because as I kid I remember on the flip side when they were warning me we were going to go into an ice age. . . . I wish people would make up their mind. It’s the control freaks, the people who want to control my life, want to control my lifestyle.",
role: "House",
lastname: "Schweikert",
firstname: "David",
party: "R",
district: 6
},
{
twitter: "RepJeffDenham",
denierquoteurl: "http://www.mercurynews.com/education/ci_8269190?nclick_check=1",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412403.jpg",
state: "CA",
denierstatement: "Some wouldn’t view them as skeptics. Some would view them as the right side of the issue. We don’t have complete factual information yet. From what I have seen the Earth has heated and cooled on its own for centuries. I don’t know that there’s anything that is a direct cause of that right now, but we can do a better job of cleaning up our planet.'",
role: "House",
lastname: "Denham",
firstname: "Jeff",
party: "R",
district: 10
},
{
twitter: "Rep_Hunter",
denierquoteurl: "http://www.eastcountymagazine.org/?q=node/1795",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412283.jpg",
state: "CA",
denierstatement: "Hunter ridiculed the notion that climate change needs to be addressed by Congress. “Nobody really knows the cause,” he said. “The earth cools, the earth warms…It could be caused by carbon dioxide or methane. Maybe we should kill the cows to stop the methane, or stop breathing to stop the CO2…Thousands of people die every year of cold, so if we had global warming it would save lives…We ought to look out for people. The earth can take care of itself.” ",
role: "House",
lastname: "Hunter",
firstname: "Duncan",
party: "R",
district: 50
},
{
twitter: "DarrellIssa",
denierquoteurl: "http://web.archive.org/web/20100320072049/http://issa.house.gov/index.php?option=com_content&view=article&id=207:global-climate-change&catid=40",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400196.jpg",
state: "CA",
denierstatement: "One of the difficulties in examining the issue of the climate change and greenhouse gases is that there is a wide range of scientific opinion on this issue and the science community does not agree to the extent of the problem or the critical threshold of when this problem is truly catastrophic.",
role: "House",
lastname: "Issa",
firstname: "Darrell",
party: "R",
district: 49
},
{
twitter: "RepLaMalfa",
denierquoteurl: "http://grist.org/list/doug-lamalfa-is-the-archetypal-climate-denying-idio/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412510.jpg",
state: "CA",
denierstatement: "It’s “bad science.” It’s “Al Gore.” It’s a “naturally occurring cycle.” You should “look at the numbers.”",
role: "House",
lastname: "LaMalfa",
firstname: "Doug",
party: "R",
district: 1
},
{
twitter: "RepMcClintock",
denierquoteurl: "http://www.youtube.com/watch?v=mFaGWHs8WqU",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412295.jpg",
state: "CA",
denierstatement: "We're all told of course the debate is over and that all the scientists agree... and as all of you know, that is succinctly not the case.'",
role: "House",
lastname: "McClintock",
firstname: "Tom",
party: "R",
district: 4
},
{
twitter: "Rep_DevinNunes",
denierquoteurl: "http://votesmart.org/public-statement/353529/#.UYPgoyvwIxE",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400297.jpg",
state: "CA",
denierstatement: "However, scientists admit that they cannot be sure whether the Earth’s temperature is rising due to cyclical warming and cooling processes, or whether and how much humans are influencing it.'",
role: "House",
lastname: "Nunes",
firstname: "Devin",
party: "R",
district: 22
},
{
twitter: "DanaRohrabacher",
denierquoteurl: "http://rohrabacher.house.gov/issue/global-warming",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400343.jpg",
state: "CA",
denierstatement: "Too often, when congress is asked to pass environmental legislation, the legislation is based on emotional junk science rather than data based on reproducable, rigorous, tested, peer-reviewed results. In no area has this been more obvious than climate change. Because the Kyoto Treaty and much of the suggested environmental legislation would decimate jobs in southern California, constituents may be interested to learn of the growing scientific consensus that global warming is not manmade, if it is in fact even occuring.'",
role: "House",
lastname: "Rohrabacher",
firstname: "Dana",
party: "R",
district: 48
},
{
twitter: "RepMikeCoffman",
denierquoteurl: "http://www.theatlantic.com/national/archive/2012/06/as-politicians-debate-climate-change-our-forests-wither/258549/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412271.jpg",
state: "CO",
denierstatement: "Climate change is naturally occurring. What influence do we have over that, we certainly need to look into, but that's subject to debate.",
role: "House",
lastname: "Coffman",
firstname: "Mike",
party: "R",
district: 6
},
{
twitter: "repcorygardner",
denierquoteurl: "http://www.nytimes.com/2011/03/09/science/earth/09climate.html?_r=1; Fort Collins Coloradoan",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412406.jpg",
state: "CO",
denierstatement: "Representative Cory Gardner, a freshman Republican from Colorado and a skeptic of human-caused global warming... '“I think the climate is changing, but I don’t believe humans are causing that change to the extent that’s been in the news.'",
role: "House",
lastname: "Gardner",
firstname: "Cory",
party: "R",
district: 4
},
{
twitter: "RepDLamborn",
denierquoteurl: "http://www.themountainmail.com/news/article_61e3ab96-cc59-11e2-a968-0019bb30f31a.html",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412191.jpg",
state: "CO",
denierstatement: "Lamborn said there are “a lot of contentious facts and claims about global warming and whether it is man made.” However, he said there is “not much unanimity” about it. At that statement many audience members commented that 98 percent was “pretty unanimous.” Lamborn said he spoke to a scientist who believes that global warming is man-made and “should materialize” 50-100 years from now. He said there are issues that need dealing with now. Eckler asked again if he would listen to the evidence claiming global warming is here and now. After more back-and-forth on the issue, Lamborn said, “I think we’ve beaten this horse to a pulp. I’m listening to all sides.”",
role: "House",
lastname: "Lamborn",
firstname: "Doug",
party: "R",
district: 5
},
{
twitter: "RepTipton",
denierquoteurl: "http://thinkprogress.org/climate/2012/08/23/734181/scott-tipton-climate-change/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412405.jpg",
state: "CO",
denierstatement: "Scott Tipton (R-CO) conceded that climate change exists, but argued that it’s caused by natural climate cycles rather than humans. “Here in the state of Colorado as our tree rings demonstrate, we’ve had droughts long before there were very many people here,” the Tea Party freshman argued. Acknowledging that humans can affect the climate is futile because it would “divide America,” said Tipton.",
role: "House",
lastname: "Tipton",
firstname: "Scott",
party: "R",
district: 3
},
{
denierquoteurl: "http://www.youtube.com/watch?v=sEdevhT6aGY",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400279.jpg",
state: "FL",
denierstatement: "\"I have scientists that I rely on, the scientists that I rely on say our climate has changed,\” Miller said. \“It wasn’t just a few years ago, what was the problem that existed? It wasn’t global warming, we were gonna all be an ice cube. We’re not ice cubes. Our climate will continue to change because of the way God formed the earth.\"",
role: "House",
lastname: "Miller",
firstname: "Jeff",
party: "R",
district: 1
},
{
twitter: "RepDennisRoss",
denierquoteurl: "http://thinkprogress.org/climate/2014/03/21/3417465/dennis-ross-climate-change/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412411.jpg",
state: "FL",
denierstatement: "I think we are contributing to some climate change, but I am not accepting all the theories that are out there that say climate change is what it is because of us.",
role: "House",
lastname: "Ross",
firstname: "Dennis",
party: "R",
district: 15
},
{
twitter: "SenRubioPress",
denierquoteurl: "http://tbo.com/ap/politics/rubio-questions-climate-change-83470",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412491.jpg",
state: "FL",
denierstatement: "The government can’t change the weather. I said that in the speech. We can pass a bunch of laws that will destroy our economy, but it isn’t going to change the weather. --- 'I don't think there's the scientific evidence to justify it,' he told the Tampa Tribune",
role: "Senate",
lastname: "Rubio",
firstname: "Marco",
party: "R"
},
{
twitter: "RepTedYoho",
denierquoteurl: "http://thinkprogress.org/climate/2014/04/15/3426668/ted-yoho-climate-denier/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412525.jpg",
state: "FL",
denierstatement: "I think it’s a natural occurrence....I think there’s an agenda-driven science. I can read stuff that says that the information was skewed. It’s not right.",
role: "House",
lastname: "Yoho",
firstname: "Ted",
party: "R",
district: 3
},
{
twitter: "RepPaulBrounMD",
denierquoteurl: "http://thinkprogress.org/politics/2009/06/26/47862/broun-globalwarming-hoax/?mobile=nc ---- http://www.youtube.com/watch?v=PPimawyrV54",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412252.jpg",
state: "GA",
denierstatement: "In June 2009, Broun received a standing ovation when he said that global warming is a 'hoax'. He said 'Scientists all over this world say that the idea of human induced global climate change is one of the greatest hoaxes perpetrated out of the scientific community. It is a hoax. There is no scientific consensus.'",
role: "House",
lastname: "Broun",
firstname: "Paul",
party: "R",
district: 10
},
{
twitter: "RepDougCollins",
denierquoteurl: "http://votesmart.org/candidate/political-courage-test/67851/doug-collins/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412531.jpg",
state: "GA",
denierstatement: "When asked if he believes human activity is contributing to climate change, Representative Collins answered “no.”",
role: "House",
lastname: "Collins",
firstname: "Doug",
party: "R",
district: 9
},
{
twitter: "RepPhilGingrey",
denierquoteurl: "http://www.epa.gov/climatechange/Downloads/endangerment/Petition_for_Reconsideration_Southeastern_Legal_Foundation.pdf",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400151.jpg",
state: "GA",
denierstatement: "Filed petition with EPA claiming: 'Climategate reveals a serious lack of integrity in the underlying data and models, such that it is doubtful that any process can be trusted until the data and models are validated and their integrity assured'",
role: "House",
lastname: "Gingrey",
firstname: "Phil",
party: "R",
district: 11
},
{
twitter: "SenatorIsakson",
denierquoteurl: "http://votesmart.org/public-statement/580879/issue-position-energy-and-the-environment#.UYZ5_LXvuSo",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400194.jpg",
state: "GA",
denierstatement: "Science has shown us that there has been a gradual warming of the earth over the last 50 years. What is not as clear is whether the cause for this warming is man-made emissions, a cyclical warming of the planet, or a combination of both. Given the uncertainty in the science behind climate change, I believe that we should take proactive steps, both personally and as a nation, to reduce our emissions footprint.'",
role: "Senate",
lastname: "Isakson",
firstname: "John",
party: "R"
},
{
twitter: "JackKingston",
denierquoteurl: "http://kingston.house.gov/news/documentsingle.aspx?DocumentID=193226",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400221.jpg",
state: "GA",
denierstatement: "We have a moral duty to be good stewards of the environment but growing the government’s coffers and killing jobs based on questionable science is a bridge too far.'",
role: "House",
lastname: "Kingston",
firstname: "Jack",
party: "R",
district: 1
},
{
twitter: "RepTomPrice",
denierquoteurl: "http://rsc.scalise.house.gov/news/documentprint.aspx?DocumentID=174274",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400626.jpg",
state: "GA",
denierstatement: "This decision goes against all common sense, especially considering the many recent revelations of errors and obfuscation in the allegedly ‘settled science’ of global warming.'",
role: "House",
lastname: "Price",
firstname: "Tom",
party: "R",
district: 6
},
{
twitter: "repwestmoreland",
denierquoteurl: "http://jacksonville.com/apnews/stories/032207/D8O1EO903.shtml; http://www.epa.gov/climatechange/Downloads/endangerment/Petition_for_Reconsideration_Southeastern_Legal_Foundation.pdf",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400627.jpg",
state: "GA",
denierstatement: "Westmoreland, who isn’t convinced that global warming is occurring, denied that he was trying to divert attention from Gore’s testimony. Also Filed petition with EPA claiming: 'Climategate reveals a serious lack of integrity in the underlying data and models, such that it is doubtful that any process can be trusted until the data and models are validated and their integrity assured'",
role: "House",
lastname: "Westmoreland",
firstname: "Lynn",
party: "R",
district: 3
},
{
twitter: "ChuckGrassley",
denierquoteurl: "http://grist.org/article/2009-08-26-chuck-grassley-does-not-believe-in-the-threat-of-anthropogenic-c/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/300048.jpg",
state: "IA",
denierstatement: "But the scientific aspect that I still reserving judgment on is the extent to which it’s manmade or natural. And it’s reasonable, considering that there’s at least a natural factor in it, because historically, and you can go to the core drillings in the glaciers to get proof of this, that we’ve had decades and decades, and maybe even centuries of periods of time when there’s been a tremendous rise in temperature, and then a tremendous fall in temperature. And all you’ve got to do is look at the little ice age of the mid-last millennia as an example. And so we’ve got to single out what’s natural and what’s manmade before you can make policy.'",
role: "Senate",
lastname: "Grassley",
firstname: "Chuck",
party: "R"
},
{
twitter: "stevekingia",
denierquoteurl: "http://thinkprogress.org/climate/2010/08/18/174777/rep-steve-king-unloads-on-climate-change-scientists-frauds-practicing-modern-version-of-the-rain-dance/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400220.jpg",
state: "IA",
denierstatement: "There are a couple of German engineers that took that theory apart and proved it wrong in a lab. I’ve read through that, but I’d have to go back to school for a half a year or a year to tell you I followed every bit of their rationale. But the presumption of the Greenhouse Effect is at least, from what I saw, was pretty convincingly rebutted.'",
role: "House",
lastname: "King",
firstname: "Steve",
party: "R",
district: 4
},
{
twitter: "mikecrapo",
denierquoteurl: "http://web.archive.org/web/20130221211520/http://www.crapo.senate.gov/issues/energy/ClimateChange.cfm",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/300030.jpg",
state: "ID",
denierstatement: "While there is no dispute over the fact that the Earth’s climate has changed many times over the planet’s history, the underlying cause of these climactic shifts is ultimately not well-understood and is a matter of vigorous debate.'",
role: "Senate",
lastname: "Crapo",
firstname: "Michael",
party: "R"
},
{
twitter: "RodneyDavis",
denierquoteurl: "http://will.illinois.edu/focus/program/talk-to-the-candidate-rodney-davis-r-13th-illinois-congressional-district",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412536.jpg",
state: "IL",
denierstatement: "During an interview with Illinois Public Media radio, a constituent asked Representative Rodney Davis what he planned to do to combat climate change, and he responded that “global warming has stopped 16 years ago.” He then went on the say that climate change is real but the debate is over whether or not it is manmade or natural.",
role: "House",
lastname: "Davis",
firstname: "Rodney",
party: "R",
district: 13
},
{
twitter: "rephultgren",
denierquoteurl: "http://illinoisreview.typepad.com/illinoisreview/2009/12/on-the-issues-14th-congressional-district-randy-hultgren.html",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412422.jpg",
state: "IL",
denierstatement: "The greatest impact on our climate clearly is the sun, and we have very little impact on the sun and how much energy and temperature the sun is sending to the earth. We have seen clearly over thousands of years that at different times more energy has come through and different times less energy has come through, and that variation has impacted climate change. Over the thousands of years that’s been recorded we’ve had both colder times and warmer times. It happens to be that we’ve recently come out of a warmer time and now actually we’re headed in to a little bit of a colder time, the impact of the sun is much different than impact that we could have had.'",
role: "House",
lastname: "Hultgren",
firstname: "Randy",
party: "R",
district: 14
},
{
twitter: "PeterRoskam",
denierquoteurl: "http://web.archive.org/web/20070928001803/http:/www.cod.edu/courier/10.20.06/NEWS_10.20.06.pdf",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412202.jpg",
state: "IL",
denierstatement: "Roskam drew the ire of the crowd by calling global warming junk science. ",
role: "House",
lastname: "Roskam",
firstname: "Peter",
party: "R",
district: 6
},
{
twitter: "RepShimkus",
denierquoteurl: "http://www.epa.gov/climatechange/Downloads/endangerment/Petition_for_Reconsideration_Southeastern_Legal_Foundation.pdf",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400373.jpg",
state: "IL",
denierstatement: "Filed petition with EPA claiming: 'Climategate reveals a serious lack of integrity in the underlying data and models, such that it is doubtful that any process can be trusted until the data and models are validated and their integrity assured'",
role: "House",
lastname: "Shimkus",
firstname: "John",
party: "R",
district: 15
},
{
twitter: "RepLarryBucshon",
denierquoteurl: "http://web.archive.org/web/20101028214947/http://www.bucshonforcongress.com/issues",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412427.jpg",
state: "IN",
denierstatement: "The data does not support the premise that carbon dioxide emissions are playing a significant role in the world temperature variations. The temperature of the Earth has been changing over centuries with warmer and colder periods throughout history.'",
role: "House",
lastname: "Bucshon",
firstname: "Larry",
party: "R",
district: 8
},
{
twitter: "ToddRokita",
denierquoteurl: "http://www.huffingtonpost.com/2013/08/26/todd-rokita-climate-change_n_3817215.html?1377534214",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412426.jpg",
state: "IN",
denierstatement: "I think it’s arrogant that we think as people that we can somehow change the climate of the whole earth when science is telling us that there’s a cycle to all this.",
role: "House",
lastname: "Rokita",
firstname: "Todd",
party: "R",
district: 4
},
{
twitter: "RepToddYoung",
denierquoteurl: "http://www.nytimes.com/2010/10/21/us/politics/21climate.html?_r=0",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412428.jpg",
state: "IN",
denierstatement: "“The science is not settled.”",
role: "House",
lastname: "Young",
firstname: "Todd",
party: "R",
district: 9
},
{
twitter: "RepLynnJenkins",
denierquoteurl: "https://twitter.com/RepLynnJenkins/status/9942721277",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412284.jpg",
state: "KS",
denierstatement: " I cosponsored a res. overturning an EPA rule that says man-made greenhouse gas emissions are a danger to public health. ",
role: "House",
lastname: "Jenkins",
firstname: "Lynn",
party: "R",
district: 2
},
{
twitter: "senpatroberts",
denierquoteurl: "http://cjonline.com/news/state/2010-08-24/oil_gas_industry_its_not_our_fault",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/300083.jpg",
state: "KS",
denierstatement: "There’s no question there’s some global warming, but I’m not sure what it means. A lot of this is condescending elitism.'",
role: "Senate",
lastname: "Roberts",
firstname: "Pat",
party: "R"
},
{
denierquoteurl: "http://www.washingtontimes.com/blog/inside-politics/2013/jan/22/rep-massie-mit-grad-questions-obamas-global-warmin/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412503.jpg",
state: "KY",
denierstatement: "Rep. Thomas Massie challenged President Obama to roll out the proof that humans have played a hand in climate change. Mr. Massie, a Kentucky Republican, said he was “disappointed” that the president in his second inaugural address blamed droughts on “human activity” and accused some of “denying the evidence of scientists.” “As somebody with a science-type background, I took offense at that,” Mr. Massie said during a panel meeting billed as “Conversations With Conservatives.” “I would challenge him to show us the linkage — the undeniable linkage — between droughts and the change of weather, and some kind of human activity.”",
role: "House",
lastname: "Massie",
firstname: "Thomas",
party: "R",
district: 4
},
{
twitter: "McConnellPress",
denierquoteurl: "http://www.cincinnati.com/story/news/politics/elections/2014/03/07/mcconnell-expect-much-congress-year/6170921/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/300072.jpg",
state: "KY",
denierstatement: "For everybody who thinks it's warming, I can find somebody who thinks it isn't",
role: "Senate",
lastname: "McConnell",
firstname: "Mitch",
party: "R"
},
{
twitter: "SenRandPaul",
denierquoteurl: "http://www.youtube.com/watch?v=cmqozUC4VWk",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412492.jpg",
state: "KY",
denierstatement: "[Scientists] are making up their facts to fit their conclusions. They’ve already caught them doing this.'",
role: "Senate",
lastname: "Paul",
firstname: "Rand",
party: "R"
},
{
twitter: "repedwhitfield",
denierquoteurl: "http://whitfield.house.gov/press-release/whitfield-blasts-use-false-science-copenhagen",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400431.jpg",
state: "KY",
denierstatement: "Misrepresenting scientific research to support one’s own personal beliefs, particularly on an international stage, is dangerous, disingenuous and simply unacceptable. I call on Mr. Gore to come clean about the real science surrounding climate change and let the American people come to their own conclusions on global warming.'",
role: "House",
lastname: "Whitfield",
firstname: "Ed",
party: "R",
district: 1
},
{
denierquoteurl: "http://www.upi.com/Top_News/US/2013/04/26/Obama-agenda-group-targets-climate-denier-lawmakers/UPI-39321366959600/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412269.jpg",
state: "LA",
denierstatement: "It could be secular. It could just be a shift on the axis.'",
role: "House",
lastname: "Cassidy",
firstname: "Bill",
party: "R",
district: 6
},
{
twitter: "RepFleming",
denierquoteurl: "https://www.facebook.com/RepJohnFleming/posts/295555310545148",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412275.jpg",
state: "LA",
denierstatement: "“Quietly released scientific report without fanfare. Global warming, to the the extent that it ever existed, halted 16 years ago. So, what is Washington controlled by the radical environmental agenda?”",
role: "House",
lastname: "Fleming",
firstname: "John",
party: "R",
district: 4
},
{
twitter: "SteveScalise",
denierquoteurl: "http://www.nola.com/politics/index.ssf/2009/12/rep_scalise_voices_fresh_doubt.html",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412261.jpg",
state: "LA",
denierstatement: "Asked whether he worries that he could be wrong, Scalise cited an “increasing number of scientists who are raising major questions about the global warming theories.” ",
role: "House",
lastname: "Scalise",
firstname: "Steve",
party: "R",
district: 1
},
{
twitter: "DavidVitter",
denierquoteurl: "http://www.youtube.com/watch?feature=player_embedded&v=RpyJrJDpkxI",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400418.jpg",
state: "LA",
denierstatement: "I do not think the science clearly supports global warming theory.'",
role: "Senate",
lastname: "Vitter",
firstname: "David",
party: "R"
},
{
twitter: "repandyharrismd",
denierquoteurl: "http://www.politico.com/story/2012/11/senate-panel-democrats-bash-climate-change-deniers-84412_Page2.html#ixzz2QqbAoa00",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412434.jpg",
state: "MD",
denierstatement: "Harris said there is a recent warming trend, but “I don’t understand or know, or I don’t believe anybody really knows, how to place that in historic perspective.” He also said human contribution to climate change “is also a complex question,” and that even if humans are contributing, “can you change that contribution given that we burn a lot of carbon-based products to create the energy we need to run the economy of the world?”",
role: "House",
lastname: "Harris",
firstname: "Andy",
party: "R",
district: 1
},
{
twitter: "CongressmanDan",
denierquoteurl: "http://www.lcv.org/elections/dirty-dozen/2012/dan-benisheK.html",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412436.jpg",
state: "MI",
denierstatement: "Despite overwhelming scientific evidence that humans are contributing to climate change, Rep. Benishek has said that climate change is “all baloney” and “just some scheme.”  Pointing to his background as a general surgeon, Benishek claims he’s “a scientist” who has the expertise to know that climate change is “unproven science stuff.” ",
role: "House",
lastname: "Benishek",
firstname: "Dan",
party: "R",
district: 1
},
{
twitter: "RepDaveCamp",
denierquoteurl: "http://camp.house.gov/news/documentprint.aspx?DocumentID=116803",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400058.jpg",
state: "MI",
denierstatement: "What is the science of climate change? What can it definitively tell us? Can it say who is responsible for it? Can it tell us what impact we can have on it, and if we can, what are the results both positive and negative? From what I have read, there remains a great deal of uncertainty with regard to the scientific evidence about climate change.'",
role: "House",
lastname: "Camp",
firstname: "Dave",
party: "R",
district: 4
},
{
twitter: "rephuizenga",
denierquoteurl: "http://vote-mi.org/politicianissue.aspx?state=mi&id=mihuizengabill&issue=busenvironment",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412437.jpg",
state: "MI",
denierstatement: "Today’s global warming doomsayers simply lack the scientific evidence to support their claims. A host of leaders in the scientific community have recognized that the argument for drastic anthropogenic global warming is no longer based on science, but is being driven by irrational fanaticism.'",
role: "House",
lastname: "Huizenga",
firstname: "Bill",
party: "R",
district: 2
},
{
twitter: "CandiceMiller",
denierquoteurl: "http://candicemiller.house.gov/save-jobs-questionable-climate-rules",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400276.jpg",
state: "MI",
denierstatement: "There is little doubt that the world’s climate is changing, because the climate has always changed. Just ask the dinosaurs or remember the ice age and how huge glaciers melting and moving formed our Great Lakes. The question is whether the current climate change is human-induced.'",
role: "House",
lastname: "Miller",
firstname: "Candice",
party: "R",
district: 10
},
{
twitter: "RepFredUpton",
denierquoteurl: "http://www.youtube.com/watch?feature=player_embedded&v=kexyzUJBffE",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400414.jpg",
state: "MI",
denierstatement: "Are any of those incurred costs actually going to impact the rising temperature under debate? The answer was no. No matter what we did between now and 2050 it, it, there was no real science to verify that it would reduce the temperature rise that some predicted. And that’s why we do need hearings [on the Climategate emails].'",
role: "House",
lastname: "Upton",
firstname: "Fred",
party: "R",
district: 6
},
{
twitter: "RepWalberg",
denierquoteurl: "http://www.youtube.com/watch?v=sEKfDBRDmUM",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412213.jpg",
state: "MI",
denierstatement: "I read scientists, editors…an equal number at the very least that say just the opposite that this is something that’s gone on for eons, that we go through these cycles.'",
role: "House",
lastname: "Walberg",
firstname: "Tim",
party: "R",
district: 7
},
{
twitter: "MicheleBachmann",
denierquoteurl: "http://www.youtube.com/watch?feature=player_embedded&v=IAaDVOd2sRQ",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412216.jpg",
state: "MN",
denierstatement: "Carbon dioxide, Mister Speaker, is a natural byproduct of nature. Carbon dioxide is natural. It occurs in Earth. It is a part of the regular lifecycle of Earth. In fact, life on planet Earth can’t even exist without carbon dioxide. So necessary is it to human life, to animal life, to plant life, to the oceans, to the vegetation that’s on the Earth, to the, to the fowl that — that flies in the air, we need to have carbon dioxide as part of the fundamental lifecycle of Earth.'",
role: "House",
lastname: "Bachmann",
firstname: "Michele",
party: "R",
district: 6
},
{
twitter: "RepErikPaulsen",
denierquoteurl: "http://www.youtube.com/watch?v=4-oTaJxyUeQ",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412303.jpg",
state: "MN",
denierstatement: "When asked if human beings are contributing to global warming, Paulsen said he wasn’t smart enough to know whether that’s true or not.",
role: "House",
lastname: "Paulsen",
firstname: "Erik",
party: "R",
district: 3
},
{
twitter: "RoyBlunt",
denierquoteurl: "http://www.humanevents.com/2009/04/29/christian-leaders-condemn-hate-crimes-bill/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400034.jpg",
state: "MO",
denierstatement: "“There isn’t any real science to say we are altering the climate path of the earth.”",
role: "Senate",
lastname: "Blunt",
firstname: "Roy",
party: "R"
},
{
twitter: "RepHartzler",
denierquoteurl: "https://twitter.com/VickyHartzler/statuses/6709535806",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412444.jpg",
state: "MO",
denierstatement: "Enjoying another beautiful global warming day in Missouri! Rep. Skelton and the UN Summit need to quit their dist. of wealth for a hoax.'",
role: "House",
lastname: "Hartzler",
firstname: "Vicky",
party: "R",
district: 4
},
{
denierquoteurl: "http://luetkemeyer.house.gov/news/documentprint.aspx?DocumentID=279631",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412292.jpg",
state: "MO",
denierstatement: "Luetkemeyer’s legislation would prohibit U.S. contributions to the IPCC, which is nothing more than a group of U.N. bureaucrats that supports man-made claims on global warming that many scientists disagree with…. Meanwhile, our very own Environmental Protection Agency recently reported that we are undergoing a period of worldwide cooling. ",
role: "House",
lastname: "Luetkemeyer",
firstname: "Blaine",
party: "R",
district: 3
},
{
twitter: "RepAnnWagner",
denierquoteurl: "http://blogs.riverfronttimes.com/dailyrft/2013/05/ann_wagner_climate_change_congress_missouri.php",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412548.jpg",
state: "MO",
denierstatement: "Our policy response to this dilemma should not be based on inconsistent and unsound science...'",
role: "House",
lastname: "Wagner",
firstname: "Ann",
party: "R",
district: 2
},
{
twitter: "GreggHarper",
denierquoteurl: "http://www.youtube.com/watch?v=VGgYk5H1yBo",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412280.jpg",
state: "MS",
denierstatement: "I don't believe that the science is at all settled on man-made global warming.'",
role: "House",
lastname: "Harper",
firstname: "Gregg",
party: "R",
district: 3
},
{
twitter: "senatorwicker",
denierquoteurl: "http://www.wicker.senate.gov/public/index.cfm?FuseAction=NewsRoom.WeeklyColumn&ContentRecord_id=7e3e0cae-fa4b-f8e7-68fc-295c843ad29a&Region_id=&Issue_id=e42cc24c-cff9-4687-0f46-8f8db97e111e",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400432.jpg",
state: "MS",
denierstatement: "Science shows that there is an increase of carbon dioxide in Earth’s atmosphere. But it has not been compellingly proven that mankind is responsible for the rise in atmospheric CO2, nor is it clear what impact CO2 has on Earth’s temperatures.'",
role: "Senate",
lastname: "Wicker",
firstname: "Roger",
party: "R"
},
{
twitter: "stevedaines",
denierquoteurl: "http://www.montanapublicmedia.org/2012/11/interview-with-u-s-house-candidate-steve-daines/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412549.jpg",
state: "MT",
denierstatement: "In a radio interview with Montana Public Radio, Daines admits the climate is changing but questions the impacts by man, that there is “significant debate here,” the “jury is still out,” and brings up the debate of sun/solar cycles versus greenhouse gases.",
role: "House",
lastname: "Daines",
firstname: "Steve",
party: "R"
},
{
twitter: "virginiafoxx",
denierquoteurl: "http://www.huffingtonpost.com/2011/04/07/climate-change-facts-myths_n_846255.html",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400643.jpg",
state: "NC",
denierstatement: "North Carolina Republican Virginia Foxx referenced books by climate-change skeptics and lamented that some environmentalists “think that we, human beings, have more impact on the climate and the world than God does.”",
role: "House",
lastname: "Foxx",
firstname: "Virginia",
party: "R",
district: 5
},
{
twitter: "RepRichHudson",
denierquoteurl: "http://votesmart.org/candidate/political-courage-test/136448/richard-hudson/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412550.jpg",
state: "NC",
denierstatement: "When asked if human activity is contributing to climate change, he responded no.",
role: "House",
lastname: "Hudson",
firstname: "Richard",
party: "R",
district: 8
},
{
twitter: "RepWalterJones",
denierquoteurl: "http://www.crystalcoastteaparty.com/email-from-walter-b-jones-re-global-warming/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400209.jpg",
state: "NC",
denierstatement: " “However, there is substantial disagreement regarding the extent of this warming, whether it’s caused by human activity or simply nature taking its course, and what solutions, if any, should be implemented. The bottom line is that the scientific community does not speak with one voice on this issue.”",
role: "House",
lastname: "Jones",
firstname: "Walter",
party: "R",
district: 3
},
{
twitter: "RepPittenger",
denierquoteurl: "http://pqasb.pqarchiver.com/citizen_times/access/1721457651.html?FMT=ABS&FMTS=ABS:FT&type=current&date=Oct+25%2C+2007&author=JORDAN+SCHRADER&pub=Asheville+Citizen+-+Times&edition=&startpage=A.2&desc=GOP%27s+Thomas%3A+Green+is+good",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412551.jpg",
state: "NC",
denierstatement: "We don't have the facts yet.... Those in my party understand that in some great measure this is a hoax.",
role: "House",
lastname: "Pittenger",
firstname: "Robert",
party: "R",
district: 9
},
{
twitter: "RepKevinCramer",
denierquoteurl: "http://votesmart.org/candidate/political-courage-test/444/kevin-cramer/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412555.jpg",
state: "ND",
denierstatement: "When asked if he believed that human activity is contributing to climate change, Mr. Cramer answered “no” and went on to say: “The manipulation of free markets by economic policy disguised as environmental policy based on inconclusive science should not be tolerated. Free people producing energy other free people want and are willing to pay for should be the core of U.S. energy policy.”",
role: "House",
lastname: "Cramer",
firstname: "Kevin",
party: "R"
},
{
twitter: "SenJohnHoeven",
denierquoteurl: "http://www.epw.senate.gov/public/index.cfm?FuseAction=Hearings.LiveStream&Hearing_id=7badef5f-802a-23ad-4525-e7f73ab98c63%2520(at%2520105:45)",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412494.jpg",
state: "ND",
denierstatement: "Well, the science shows that there’s warming. There’s different opinions of exactly what’s causing it.'",
role: "Senate",
lastname: "Hoeven",
firstname: "John",
party: "R"
},
{
twitter: "SenatorFischer",
denierquoteurl: "http://www.theindependent.com/news/local/fischer-kerrey-show-stark-differences-in-senate-debate/article_e76d8368-2b37-599e-8942-29fac0dc24c4.html",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412556.jpg",
state: "NE",
denierstatement: "Asked about man-made climate change, Fischer immediately said, 'I certainly don't support cap-and-trade.' She said she believes in weather change, but she said she does not believe man has a huge impact on the climate. ",
role: "Senate",
lastname: "Fischer",
firstname: "Deb",
party: "R"
},
{
twitter: "Mike_Johanns",
denierquoteurl: "http://www.youtube.com/watch?v=b8znE2lgdGk",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412320.jpg",
state: "NE",
denierstatement: "There is a significant debate as to what role man plays in warming of the climate. ",
role: "Senate",
lastname: "Johanns",
firstname: "Mike",
party: "R"
},
{
twitter: "LEETERRYNE",
denierquoteurl: "http://www.esquire.com/blogs/politics/xl-pipeline-pros-and-cons-11446071",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400400.jpg",
state: "NE",
denierstatement: "There's an argument here on the true impact of man... Is it really 97 to 3? I don't think so.'",
role: "House",
lastname: "Terry",
firstname: "Lee",
party: "R",
district: 2
},
{
twitter: "KellyAyotte",
denierquoteurl: "http://www.seacoastonline.com/articles/20100930-NEWS-9300410",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412493.jpg",
state: "NH",
denierstatement: "Asked if she believed in climate change, she said, “there is scientific evidence that demonstrates there is some impact from human activities. However I don’t think the evidence is conclusive.” ",
role: "Senate",
lastname: "Ayotte",
firstname: "Kelly",
party: "R"
},
{
twitter: "repgarrett",
denierquoteurl: "http://www.northjersey.com/news/state/093010_QA_with_North_Jersey_Congressional_candidates_Climate_change_and_what_to_do_about_it.html",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400145.jpg",
state: "NJ",
denierstatement: "The real question that still exists in a lot of people’s minds, experts and non-experts alike, on the area of global warming and what role the government should have in this realm. … I’ve heard a number of experts on both sides of the equation on this issue and to me the evidence, the question is still out there.'",
role: "House",
lastname: "Garrett",
firstname: "Scott",
party: "R",
district: 5
},
{
twitter: "RepStevePearce",
denierquoteurl: "http://dyn.politico.com/printstory.cfm?uuid=82C45B00-18FE-70B2-A8988EFE62E30EA4",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400313.jpg",
state: "NM",
denierstatement: "“I think we ought to take a look at whatever the group is that measures all this, the IPCC, they don’t even believe the crap... why should the rest of be penalized in our standard of living for something that can’t be validated?” ",
role: "House",
lastname: "Pearce",
firstname: "Stevan",
party: "R",
district: 2
},
{
twitter: "SpeakerBoehner",
denierquoteurl: "http://abcnews.go.com/print?id=7373578",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400036.jpg",
state: "OH",
denierstatement: "George, the idea that carbon dioxide is a carcinogen that is harmful to our environment is almost comical. Every time we exhale, we exhale carbon dioxide. Every cow in the world, you know, when they do what they do, you’ve got more carbon dioxide.'",
role: "House",
lastname: "Boehner",
firstname: "John",
party: "R",
district: 8
},
{
twitter: "RepSteveChabot",
denierquoteurl: "http://stevechabot.com/blog/climate-scientists-behaving-badly/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400071.jpg",
state: "OH",
denierstatement: "Climategate is “just another example of many in the press, and many in the academic/scientific community having bought into the whole global warming/climate change ‘religion,’ no matter what the facts are.” ",
role: "House",
lastname: "Chabot",
firstname: "Steve",
party: "R",
district: 1
},
{
twitter: "repbobgibbs",
denierquoteurl: "http://www.seorf.ohiou.edu/~voters/2010primary/VoterGuide-2010.pdf",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412463.jpg",
state: "OH",
denierstatement: "It is clear that science has not been able to document what is happening and if human activity is causing a problem or not . Many scientists are on both sides of this issue and the proponents of climate change have not substantiated their findings based on sound science.'",
role: "House",
lastname: "Gibbs",
firstname: "Bob",
party: "R",
district: 7
},
{
twitter: "repbilljohnson",
denierquoteurl: "http://thinkprogress.org/climate/2013/06/06/2113571/gop-congressman-with-computer-science-degree-justifies-opposition-to-epa-rules-im-a-scientist/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412460.jpg",
state: "OH",
denierstatement: "In another, more accurate, sense, Johnson is a man with a degree in computer science who is awash in oil and gas money and denies climate science, asserting in 2011, “I am not an alarmist that believes that greenhouse gas emissions coming from the coal industry are causing major problems.”",
role: "House",
lastname: "Johnson",
firstname: "Bill",
party: "R",
district: 6
},
{
twitter: "robportman",
denierquoteurl: "http://www.dispatch.com/content/stories/insight/2010/07/25/jobs-vs--climate.html",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400325.jpg",
state: "OH",
denierstatement: "When you analyze all the data, there is a warming trend according to science. But the jury is out on the degree of how much is manmade.'",
role: "Senate",
lastname: "Portman",
firstname: "Rob",
party: "R"
},
{
twitter: "RepSteveStivers",
denierquoteurl: "http://www.nrdcactionfund.org/updates/congressional-candidates-views-on-clean-energy-climate-change-oh-15.html/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412461.jpg",
state: "OH",
denierstatement: "Disagrees with the statement: “Man-made global warming is a scientific fact.”",
role: "House",
lastname: "Stivers",
firstname: "Steve",
party: "R",
district: 15
},
{
twitter: "tiberipress",
denierquoteurl: "http://www.dispatch.com/content/stories/national_world/2009/12/20/ohwarming.ART_ART_12-20-09_A3_J4G29E7.html",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400406.jpg",
state: "OH",
denierstatement: "GOP Rep. Pat Tiberi of Genoa Township doesn’t think there is a consensus among scientists about whether global warming is proven.",
role: "House",
lastname: "Tiberi",
firstname: "Pat",
party: "R",
district: 12
},
{
twitter: "RepJBridenstine",
denierquoteurl: "http://bridenstine.house.gov/issues/energy",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412567.jpg",
state: "OK",
denierstatement: "He downplayed the need for more climate research by noting that atmospheric temperatures have not risen over the last decade, and said temperatures coincide more with solar activity than with man-made factors. “Global temperatures stopped rising 10 years ago,” he said. “Global temperature changes, when they exist, correlate with sun output and ocean cycles.” He noted the Medieval Warm Period that happened “long before cars, power plants and the industrial revolution.” And he noted the Little Ice Age, which also happened irrespective of human activity.” Even climate change alarmists admit that the number of hurricanes hitting the U.S. and the number of tornado touchdowns have been on a slow decline for over 100 years,” he said.",
role: "House",
lastname: "Bridenstine",
firstname: "Jim",
party: "R",
district: 1
},
{
twitter: "TomCoburn",
denierquoteurl: "http://normantranscript.com/x1088167215/Coburn-Americans-need-leadership-self-reliance",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400576.jpg",
state: "OK",
denierstatement: "“I’ve read the basic scientific studies, and a lot of it doesn’t add up for me,”",
role: "Senate",
lastname: "Coburn",
firstname: "Thomas",
party: "R"
},
{
twitter: "InhofePress",
denierquoteurl: "http://www.inhofe.senate.gov/epw-archive/press/bsen-inhofe-delivers-major-speech-on-the-science-of-climate-change/b-icatastrophic-global-warming-alarmism-not-based-on-objective-sciencei-ipart-2/i",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/300055.jpg",
state: "OK",
denierstatement: "I have offered compelling evidence that catastrophic global warming is a hoax. That conclusion is supported by the painstaking work of the nation's top climate scientists.'[36] ",
role: "Senate",
lastname: "Inhofe",
firstname: "Jim",
party: "R"
},
{
twitter: "replankford",
denierquoteurl: "http://www.edmondsun.com/local/x1687380598/5th-District-candidates-united-against-cap-and-trade",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412464.jpg",
state: "OK",
denierstatement: "This whole global warming myth will be exposed as what it really is — a way of control more than anything else. And that generation will be ticked.'",
role: "House",
lastname: "Lankford",
firstname: "James",
party: "R",
district: 5
},
{
twitter: "RepMullin",
denierquoteurl: "http://www.youtube.com/watch?v=c1FfLiWybmI",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412568.jpg",
state: "OK",
denierstatement: "I haven’t seen the reports that would get me to believe that anything’s different than the patterns that we have that we’ve gone through through the time of records.",
role: "House",
lastname: "Mullin",
firstname: "Markwayne",
party: "R",
district: 2
},
{
twitter: "RepLouBarletta",
denierquoteurl: "http://citizensvoice.com/news/despite-varying-views-kanjorski-barletta-agree-a-lot-on-energy-issues-1.1050145",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412469.jpg",
state: "PA",
denierstatement: "You know there's arguments on both sides. I'm not convinced that there's scientific evidence that proves that. I believe there's some that can also argue the opposite,' he said.",
role: "House",
lastname: "Barletta",
firstname: "Lou",
party: "R",
district: 11
},
{
twitter: "RepScottPerry",
denierquoteurl: "http://www.yorkblog.com/ydrpolitics/2012/09/20/how-much-do-people-contribute-to-global-warming-congressional-candidates-for-york-county-weigh-in/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412569.jpg",
state: "PA",
denierstatement: "I do believe global warming is occurring. …However, I do take exception, whether it’s man-made or not",
role: "House",
lastname: "Perry",
firstname: "Scott",
party: "R",
district: 4
},
{
twitter: "KeithRothfus",
denierquoteurl: "http://www.youtube.com/watch?v=UEUA2MYRI8U",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412570.jpg",
state: "PA",
denierstatement: "When asked, 'Do you believe that global warming which is now referred to as climate change is a fact, and if so do you believe that it is man-made?' Rothfus responded, 'I do not believe it’s man-made and I am not convinced that it is a fact. I think the science is still out. I think for the last 15 years we haven’t had any warming.'",
role: "House",
lastname: "Rothfus",
firstname: "Keith",
party: "R",
district: 12
},
{
twitter: "CongressmanGT",
denierquoteurl: "http://www.gpo.gov/fdsys/pkg/CREC-2009-06-02/html/CREC-2009-06-02-pt1-PgH6063.htm",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412317.jpg",
state: "PA",
denierstatement: "In the debate and most of the debate of the majority party here, it’s not so much based on real science as political science or even, to some degree, science fiction. And so, to look at why this–and I looked at every piece of legislation in terms of cost benefits. And when we look at the benefits of this, I think human activity, it’s acknowledged, does contribute towards carbon dioxide emissions. But it’s less than 4 percent. To put that into perspective, forest fires, wildfires contribute 10 percent of CO2 emissions. And so not even with the debate of, you know, are we warming the Earth or not warming the Earth, there’s a lot of smart folks out there that are publishing research or earning their dissertations based on debating that science. But what the experts agree upon, the researchers agree is, human activity is less than 4 percent contributes towards CO2 emissions.'",
role: "House",
lastname: "Thompson",
firstname: "Glenn",
party: "R",
district: 5
},
{
twitter: "SenToomey",
denierquoteurl: "http://www.youtube.com/watch?feature=player_embedded&v=rlYlvR5x8F4",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400408.jpg",
state: "PA",
denierstatement: "My view is: I think the data is pretty clear. There has been an increase in the surface temperature of the planet over the course of the last 100 years or so. I think it’s clear that that has happened. The extent to which that has been caused by human activity I think is not as clear. I think that is still very much disputed and has been debated.'",
role: "Senate",
lastname: "Toomey",
firstname: "Pat",
party: "R"
},
{
denierquoteurl: "http://www.youtube.com/watch?v=HK_TFWg7hwI",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412472.jpg",
state: "SC",
denierstatement: "I don't believe in climate change. I don't believe in man-I believe the climate is changing, but I don't believe it's man driven.",
role: "House",
lastname: "Duncan",
firstname: "Jeff",
party: "R",
district: 3
},
{
twitter: "tgowdysc",
denierquoteurl: "http://www.goupstate.com/article/20100523/NEWS/100529899?p=1&tc=pg",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412473.jpg",
state: "SC",
denierstatement: "Global warming has not been proven to the satisfaction of the constituents I seek to serve.'",
role: "House",
lastname: "Gowdy",
firstname: "Trey",
party: "R",
district: 4
},
{
twitter: "repmickmulvaney",
denierquoteurl: "http://www.mulvaneyforcongress.com/issues-2/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412474.jpg",
state: "SC",
denierstatement: "Energy independence, green technology, and innovation is something we should pursue as a nation. However, we shouldn’t seek to accomplish that by taxing people based on questionable science. Neither should we ignore domestic energy resources – coal, natural gas, oil – because of baseless claims regarding global warming.'",
role: "House",
lastname: "Mulvaney",
firstname: "Mick",
party: "R",
district: 5
},
{
twitter: "USRepJoeWilson",
denierquoteurl: "http://votesmart.org/candidate/political-courage-test/3985/joe-wilson-sr/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400433.jpg",
state: "SC",
denierstatement: "When asked if he believes that human activity is contributing to climate change, Rep. Wilson answered “no.”",
role: "House",
lastname: "Wilson",
firstname: "Joe",
party: "R",
district: 2
},
{
twitter: "repkristinoem",
denierquoteurl: "http://web.archive.org/web/20110708024436/http://badlandsblue.blogspot.com/2010/08/snooki-noem-resolves-astrology-creates.html",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412475.jpg",
state: "SD",
denierstatement: "Voted for an SD House Resolution stating that: 'That there are a variety of climatological, meteorological, astrological, thermological, cosmological, and ecological dynamics that can effect world weather phenomena and that the significance and interrelativity of these factors is largely speculative'",
role: "House",
lastname: "Noem",
firstname: "Kristi",
party: "R"
},
{
twitter: "MarshaBlackburn",
denierquoteurl: "http://www.youtube.com/watch?feature=player_embedded&v=Vzj0kXq8E4g",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400032.jpg",
state: "TN",
denierstatement: "Also absent from the discussion in Copenhagen is the climate-gate scandal. Recently leaked e-mails reveal climate scientists have a long track record of manipulating data to hide scientific evidence that contradicts the global warming establishment. And why? To bully citizens and lawmakers into supporting job-killing energy tax schemes. This scandal raises serious questions about the Democrat’s climate control plans, questions that deserve a transparent investigation, not a rush to judgement by the bureaucrats in Copenhagen.'",
role: "House",
lastname: "Blackburn",
firstname: "Marsha",
party: "R",
district: 7
},
{
twitter: "RepJeffDuncan",
denierquoteurl: "http://duncan.house.gov/issue/environment-and-global-warming",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400116.jpg",
state: "TN",
denierstatement: "Supports claim that global warming is “the greatest scam in history.”",
role: "House",
lastname: "Duncan",
firstname: "John",
party: "R",
district: 2
},
{
twitter: "DrPhilRoe",
denierquoteurl: "http://votesmart.org/public-statement/549174/#.UYcUi7XvuSo",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412310.jpg",
state: "TN",
denierstatement: "Many believe greenhouse gas emissions are contributing to the gradual warming of our planet and changing of our climate. While there are many questions surrounding the science of the issue, it seems to me like we could develop a solution that will reduce greenhouse gas emissions without inflicting catastrophic damage on our economy.'",
role: "House",
lastname: "Roe",
firstname: "Phil",
party: "R",
district: 1
},
{
twitter: "RepJoeBarton",
denierquoteurl: "http://www.nbcnews.com/id/17718399/#.UYaYp7XvuSo",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400018.jpg",
state: "TX",
denierstatement: "“You’re not just off a little, you’re totally wrong,” Barton said as he challenged Gore’s conclusion that carbon dioxide emissions cause rising global temperatures.",
role: "House",
lastname: "Barton",
firstname: "Joe",
party: "R",
district: 6
},
{
twitter: "RepKevinBrady",
denierquoteurl: "http://www.epa.gov/climatechange/Downloads/endangerment/Petition_for_Reconsideration_Southeastern_Legal_Foundation.pdf",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400046.jpg",
state: "TX",
denierstatement: "Climategate reveals a serious lack of integrity in the underlying data and models, such that it is doubtful that any process can be trusted until the data and models are validated and their integrity assured.'",
role: "House",
lastname: "Brady",
firstname: "Kevin",
party: "R",
district: 8
},
{
twitter: "michaelcburgess",
denierquoteurl: "http://www.gpo.gov/fdsys/pkg/CHRG-112hhrg66704/html/CHRG-112hhrg66704.htm",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400052.jpg",
state: "TX",
denierstatement: "“My opinion, for what it is worth, is that the science behind global temperature changes is not settled.”",
role: "House",
lastname: "Burgess",
firstname: "Michael",
party: "R",
district: 26
},
{
twitter: "JudgeCarter",
denierquoteurl: "http://carter.house.gov/op-eds/the-return-of-the-warmers/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400068.jpg",
state: "TX",
denierstatement: "“Global warming is simply a chicken-little scheme to use mass media and government propaganda to convince the world that destruction of individual liberties and national sovereignty is necessary to save mankind, and that the unwashed masses would destroy themselves without the enlightened global dictatorship of these frauds.”",
role: "House",
lastname: "Carter",
firstname: "John",
party: "R",
district: 31
},
{
twitter: "ConawayTX11",
denierquoteurl: "http://www.youtube.com/watch?v=lIpqErN9LJU",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400655.jpg",
state: "TX",
denierstatement: "Science is never settled…they changed the phraseology because the climate isn’t warming. ",
role: "House",
lastname: "Conaway",
firstname: "Michael",
party: "R",
district: 11
},
{
twitter: "JohnCornyn",
denierquoteurl: "http://www.cornyn.senate.gov/public/index.cfm?p=NewsReleases&ContentRecord_id=4d678d77-cf3a-483d-b55a-426830c34b42&ContentType_id=b94acc28-404a-4fc6-b143-a9e15bf92da4&Group_id=24eb5606-e2db-4d7f-bf6c-efc5df80b676&MonthDisplay=12&YearDisplay=2009",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/300027.jpg",
state: "TX",
denierstatement: "“Taxpayer funded research by NASA and the Goddard Institute for Space Studies (GISS) concerning the warmest years on record has been the subject of dispute and after challenges, has been changed and re-released. What is less known is why the changes were made and what inherent flaws existed in the original data, if any. It is important to understand the reasons behind these alterations and further to avoid suspicion that data was massaged to fit the prescribed theory that global warming is attributable to man-made greenhouse gas emissions.”",
role: "Senate",
lastname: "Cornyn",
firstname: "John",
party: "R"
},
{
twitter: "SenTedCruz",
denierquoteurl: "http://c3.thevoterguide.org/v/dallas12/race-detail.do?id=10253526",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412573.jpg",
state: "TX",
denierstatement: "There remains considerable uncertainty about the effect of the many factors that influence climate: the sun, the oceans, clouds, the behavior of water vapor (the main greenhouse gas), volcanic activity, and human activity. Nonetheless, climate-change proponents based their models on assumptions about those factors, and now we know that many of those assumptions were wrong.'",
role: "Senate",
lastname: "Cruz",
firstname: "Ted",
party: "R"
},
{
twitter: "congculberson",
denierquoteurl: "http://culberson.house.gov/hold-your-breath-texas/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400089.jpg",
state: "TX",
denierstatement: "This week the Environmental Protection Agency (EPA) decided that the air we exhale, carbon dioxide, is toxic and poses a danger to our well-being…. While this blatant power grab is disappointing, the truly alarming part is that the scientific evidence the EPA used to support its conclusion comes directly from United Nations (U.N.) climate data – the same data that were recently found to have been deliberately manipulated to support the global warming movement. When EPA Administrator Lisa Jackson announced the proposed endangerment finding in April, she readily admitted that the agency “relied heavily upon the major findings and conclusions from recent assessments of the U.S. Climate Change Science Program and the Intergovernmental Panel on Climate Change.” Emails recently made public offer definitive proof of a collective effort among some U.N. scientists to misrepresent climate data in order to foist their political agenda onto the public.'",
role: "House",
lastname: "Culberson",
firstname: "John",
party: "R",
district: 7
},
{
twitter: "farenthold",
denierquoteurl: "http://blake.com/?page_id=271",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412482.jpg",
state: "TX",
denierstatement: "Global warming is scare tactic used by groups with a political agenda. [sic]'",
role: "House",
lastname: "Farenthold",
firstname: "Blake",
party: "R",
district: 27
},
{
twitter: "RepBillFlores",
denierquoteurl: "http://web.archive.org/web/20111218171003/http://www.billfloresforcongress.com/energy",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412480.jpg",
state: "TX",
denierstatement: "It is time we stopped putting petty politics based on dubious “agenda-driven, scientific” research ahead of creating more American energy. ",
role: "House",
lastname: "Flores",
firstname: "Bill",
party: "R",
district: 17
},
{
twitter: "replouiegohmert",
denierquoteurl: "http://www.youtube.com/watch?v=r7qMnuob5P4",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400651.jpg",
state: "TX",
denierstatement: "We’re finding out the world is staying the same or actually cooling.'",
role: "House",
lastname: "Gohmert",
firstname: "Louie",
party: "R",
district: 1
},
{
twitter: "RalphHallPress",
denierquoteurl: "http://news.sciencemag.org/scienceinsider/2011/12/ralph-hall-speaks-out-on-climate.html",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400165.jpg",
state: "TX",
denierstatement: "I'm really more fearful of freezing. And I don't have any science to prove that. But we have a lot of science that tells us they're not basing it on real scientific facts'",
role: "House",
lastname: "Hall",
firstname: "Ralph",
party: "R",
district: 4
},
{
twitter: "RandyNeugebauer",
denierquoteurl: "http://randy.house.gov/randys-roundup/afghanistan-decision-approaches",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400441.jpg",
state: "TX",
denierstatement: "What we have here is a case of formulating scientific findings that back up policy, instead of creating policy that is backed up by legitimate science. Proponents of man-made global warming in Congress will use every opportunity they have to invite witnesses to testify before Congress who only share their point of view. We now have clear evidence of what we knew all along, that there are perhaps thousands of scientists who don’t share these views, and sadly have been the subject of concerted efforts to discourage and suppress their findings from publication.'",
role: "House",
lastname: "Neugebauer",
firstname: "Randy",
party: "R",
district: 19
},
{
twitter: "OlsonPressShop",
denierquoteurl: "http://www.c-spanvideo.org/clip/3680018",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412302.jpg",
state: "TX",
denierstatement: "The emails that emerge from the University of East Anglia call into question the accuracy of the IPCC data.'",
role: "House",
lastname: "Olson",
firstname: "Pete",
party: "R",
district: 22
},
{
twitter: "JudgeTedPoe",
denierquoteurl: "http://www.gpo.gov/fdsys/pkg/CREC-2009-12-15/html/CREC-2009-12-15-pt1-PgH14948.htm",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400652.jpg",
state: "TX",
denierstatement: "The consensus has been for some time that global warming, climate change, continues because man is the perpetrator. Now we are beginning to learn that may not be true, that there is not a consensus that there is global warming or climate change. We now have heard about Climategate, where the expert scientists hid emails in England that disagreed with the so-called consensus that there is global warming and global climate change. We have heard now new evidence that even NASA is involved in not revealing evidence that contradicts climate change. ",
role: "House",
lastname: "Poe",
firstname: "Ted",
party: "R",
district: 2
},
{
twitter: "LamarSmithTX21",
denierquoteurl: "http://www.mysanantonio.com/news/news_columnists/o_ricardo_pimentel/article/Will-climate-change-change-Lamar-Smith-4098255.php",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400381.jpg",
state: "TX",
denierstatement: "“I believe climate change is due to a combination of factors, including natural cycles, sun spots and human activity. But scientists still don't know for certain how much each of these factors contributes to the overall climate change that the Earth is experiencing,” he said in a statement (San Antonio Express-News, 12/6/12)",
role: "House",
lastname: "Smith",
firstname: "Lamar",
party: "R",
district: 21
},
{
twitter: "SteveStockmanTX",
denierquoteurl: "http://www.youtube.com/watch?v=1rXEIeyUjRw",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/410396.jpg",
state: "TX",
denierstatement: "“The new fad thing that’s going through America and around the world. It’s called global warming.”",
role: "House",
lastname: "Stockman",
firstname: "Steve",
party: "R",
district: 36
},
{
twitter: "MacTXPress",
denierquoteurl: "https://thornberry.house.gov/emailarchive/26.htm",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400404.jpg",
state: "TX",
denierstatement: "Global Warming: Politics or Science? Some scientists believe that the temperature of the Earth is increasing rapidly. Others, such as those at the United Kingdom’s Hadley Center for Climate Studies, say that the Earth’s temperature is not much different now than it was 50 or 100 years ago. The case that man is causing any change in temperature is even more hotly contested.'",
role: "House",
lastname: "Thornberry",
firstname: "Mac",
party: "R",
district: 13
},
{
twitter: "jasoninthehouse",
denierquoteurl: "http://www.heraldextra.com/news/local/article_661bd2ba-a341-5940-aa5c-f3d765ac6155.html",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412270.jpg",
state: "UT",
denierstatement: " Chaffetz lambasts global warming (calling it “a farce”). ",
role: "House",
lastname: "Chaffetz",
firstname: "Jason",
party: "R",
district: 3
},
{
twitter: "SenOrrinHatch",
denierquoteurl: "http://web.archive.org/web/20091201233001/http://hatch.senate.gov/public/index.cfm?FuseAction=Issuepositions.Home",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/300052.jpg",
state: "UT",
denierstatement: "There is also some disagreement among scientists as to whether global warming – regardless of its cause – would result in a net benefit or detriment to life on earth. Scientific studies demonstrate overwhelmingly that humans tend to fare better during warming spells than periods of cooling.'",
role: "Senate",
lastname: "Hatch",
firstname: "Orrin",
party: "R"
},
{
twitter: "repchrisstewart",
denierquoteurl: "http://www.sltrib.com/sltrib/opinion/56130738-82/climate-global-stewart-regarding.html.csp",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412581.jpg",
state: "UT",
denierstatement: "The science regarding climate change is anything but settled. '",
role: "House",
lastname: "Stewart",
firstname: "Chris",
party: "R",
district: 2
},
{
twitter: "Randy_Forbes",
denierquoteurl: "http://www.timesdispatch.com/business/article_c99f5f98-f5f0-5f0b-8ccc-7b2cce7a8a72.html",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400137.jpg",
state: "VA",
denierstatement: "Elected officials need to depend on experts in the field to make determinations on the degree to which our planet is warming, and there is evidence among scientists and researchers pointing in both directions. ",
role: "House",
lastname: "Forbes",
firstname: "Randy",
party: "R",
district: 4
},
{
twitter: "RepMGriffith",
denierquoteurl: "http://www.youtube.com/watch?v=Y1MUMKQlLtM",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412485.jpg",
state: "VA",
denierstatement: "[Climate Change] led to the Vikings dominating Europe for several hundred years.'",
role: "House",
lastname: "Griffith",
firstname: "Morgan",
party: "R",
district: 9
},
{
twitter: "RepRobertHurt",
denierquoteurl: "http://www.dailyprogress.com/news/article_d930b154-0251-55b7-a67e-d150200557f9.html",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412484.jpg",
state: "VA",
denierstatement: "Hurt said Climategate is “scientists who have given us something that is not true. It is faulty information and it has real consequences in the 5th District, in the loss of jobs and in power bills from Appalachian Power Co.”",
role: "House",
lastname: "Hurt",
firstname: "Robert",
party: "R",
district: 5
},
{
twitter: "repscottrigell",
denierquoteurl: "http://hamptonroads.com/2010/06/voter-guide-2nd-district-gop-candidates#four",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412483.jpg",
state: "VA",
denierstatement: "Does not believe that climate change is caused by human actions. ",
role: "House",
lastname: "Rigell",
firstname: "Scott",
party: "R",
district: 2
},
{
twitter: "RobWittman",
denierquoteurl: "http://www.timesdispatch.com/business/article_c99f5f98-f5f0-5f0b-8ccc-7b2cce7a8a72.html",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412255.jpg",
state: "VA",
denierstatement: "We must recognize that these climactic cycles of heating and cooling have been going on well before man appeared on earth.'",
role: "House",
lastname: "Wittman",
firstname: "Robert",
party: "R",
district: 1
},
{
twitter: "DocHastings",
denierquoteurl: "http://www.dailykos.com/story/2008/02/28/465486/-Doc-Hastings-Concedes-Global-Warming",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400171.jpg",
state: "WA",
denierstatement: "Hastings told the Columbia Basin Herald he understands global warming exists. He said the cause of global warming is the concern. Hastings said he is not convinced people and their actions are the cause of global warming and questions if it is a natural process because the earth has warmed and cooled many times throughout history.",
role: "House",
lastname: "Hastings",
firstname: "Doc",
party: "R",
district: 4
},
{
twitter: "cathymcmorris",
denierquoteurl: "http://blog.thenewstribune.com/politics/2008/05/30/cathy-mcmorris-rodgers-10-reasons-its-good-to-be-republican/#storylink=cpy",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400659.jpg",
state: "WA",
denierstatement: "We believe Al Gore deserves an ‘F’ in science and an ‘A’ in creative writing.'",
role: "House",
lastname: "McMorris Rodgers",
firstname: "Cathy",
party: "R",
district: 5
},
{
twitter: "SenRonJohnson",
denierquoteurl: "http://www.jsonline.com/multimedia/video/?bcpid=13960334001&bctid=590004292001",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412496.jpg",
state: "WI",
denierstatement: "“I absolutely do not believe in the science of man-caused climate change,” Johnson said. “It’s not proven by any stretch of the imagination. It's far more likely that it's sunspot activity or just something in the geologic eons of time.”",
role: "Senate",
lastname: "Johnson",
firstname: "Ron",
party: "R"
},
{
twitter: "reppaulryan",
denierquoteurl: "http://paulryan.house.gov/news/documentsingle.aspx?DocumentID=193671#.UYahkLXvuSo",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400351.jpg",
state: "WI",
denierstatement: " Unilateral economic restraint in the name of fighting global warming has been a tough sell in our communities, where much of the state is buried under snow. ",
role: "House",
lastname: "Ryan",
firstname: "Paul",
party: "R",
district: 1
},
{
twitter: "JimPressOffice",
denierquoteurl: "http://sensenbrenner.house.gov/UploadedFiles/WISN_Jay_Weber_-_Sensenbrenner_interview.mp3",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400365.jpg",
state: "WI",
denierstatement: "I think that the science is inconclusive on this...I personally believe that the solar flares are more responsible for climatic cycles than anything that human beings do and our lunar, our rovers on Mars have indicated that there has been a slight warming in the atmosphere of Mars and that certainly was not caused by the internal combustion engine.'",
role: "House",
lastname: "Sensenbrenner",
firstname: "James",
party: "R",
district: 5
},
{
twitter: "RepShelley",
denierquoteurl: "http://blogs.wvgazette.com/coaltattoo/2009/04/17/fact-check-capito-climate-change-and-the-carbon-cycle/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/400061.jpg",
state: "WV",
denierstatement: "Despite a widespread scientific consensus, the West Virginia Republican said she’s “not convinced” that human-caused emissions of carbon dioxide are leading to global warming that will alter the planet’s climate in ways that could be dangerous. ",
role: "House",
lastname: "Capito",
firstname: "Shelley",
party: "R",
district: 2
},
{
twitter: "RepMcKinley",
denierquoteurl: "http://blogs.wvgazette.com/coaltattoo/2010/10/20/1st-district-update-more-west-virginia-politicians-ignore-the-mounting-science-about-global-warming/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412487.jpg",
state: "WV",
denierstatement: "Many scientists have disavowed past climate change research, McKinley said, and he’s waiting for valid science to convince him there’s a problem and whether man is to blame. ",
role: "House",
lastname: "McKinley",
firstname: "David",
party: "R",
district: 1
},
{
twitter: "SenJohnBarrasso",
denierquoteurl: "http://www.eenews.net/public/EEDaily/2009/07/15/1",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412251.jpg",
state: "WY",
denierstatement: "When Barrasso was in college and medical school, he said, the 'best science at the time said that the Ice Age is coming.... So all I'm saying is, how much of the wealth of this nation are we going to put at risk for something that may be poorly spent money?'",
role: "Senate",
lastname: "Barrasso",
firstname: "John",
party: "R"
},
{
twitter: "CynthiaLummis",
denierquoteurl: "http://wyofile.com/2012/11/17804/",
status: "Denier",
photourl: "https://secure.assets.bostatic.com/apps/lincoln/media/person_photos/412294.jpg",
state: "WY",
denierstatement: "“We’re just beginning to explore what mankind’s role is in climate change, so I’d argue that the jury’s still out.”",
role: "House",
lastname: "Lummis",
firstname: "Cynthia",
party: "R"
}
];
  return seedData;
})();

module.exports = seed;

